### ISSUE TITLE
PUT not updating PostgreSQL database

### ISSUE THREAD

**Issue by rock31** [gramps-project/gramps-webapi#272] opened 2022-02-09 10:46 UTC
PUT requests to the API are not reflected in the associated PostgreSQL database. Is this the intended behaviour?

**Comment by DavidMStraub** [comment] 2022-02-09 10:55
No, definitely not intended.

Does it mean any write access fails? Also POST, DELETE?

Any errors in the log?

@Rahel-A, did it work for you or did you only test read access?

**Comment by rock31** [comment] 2022-02-09 12:01
This is the log for a PUT request to add coordinates to a place:
```
2022-02-09 11:38:08.637 UTC [759278] postgres@stammbaum LOG:  statement: SET DateStyle=ISO; SET client_min_messages=notice; SELECT set_config('bytea_output','hex',false) FROM pg_settings WHERE name = 'bytea_output'; SET client_encoding='UNICODE';
2022-02-09 11:38:08.642 UTC [759278] postgres@stammbaum LOG:  statement: SELECT version()
2022-02-09 11:38:08.643 UTC [759278] postgres@stammbaum LOG:  statement:
        SELECT
            db.oid as did, db.datname, db.datallowconn,
            pg_encoding_to_char(db.encoding) AS serverencoding,
            has_database_privilege(db.oid, 'CREATE') as cancreate, datlastsysoid,
            datistemplate
        FROM
            pg_catalog.pg_database db
        WHERE db.datname = current_database()
2022-02-09 11:38:08.645 UTC [759278] postgres@stammbaum LOG:  statement:
                SELECT
                    roles.oid as id, roles.rolname as name,
                    roles.rolsuper as is_superuser,
                    CASE WHEN roles.rolsuper THEN true ELSE roles.rolcreaterole END as
                    can_create_role,
                    CASE WHEN roles.rolsuper THEN true
                    ELSE roles.rolcreatedb END as can_create_db,
                    CASE WHEN 'pg_signal_backend'=ANY(ARRAY(
                        SELECT pg_catalog.pg_roles.rolname FROM
                        pg_catalog.pg_auth_members m JOIN pg_catalog.pg_roles ON
                        (m.roleid = pg_catalog.pg_roles.oid) WHERE
                         m.member = roles.oid)) THEN True
                    ELSE False END as can_signal_backend
                FROM
                    pg_catalog.pg_roles as roles
                WHERE
                    rolname = current_user
```
And this are the additional logs of a POST request to add a note:

```
2022-02-09 11:51:08.920 UTC [761178] postgres@stammbaum LOG:  statement: SELECT n.nspname, r.relname
        FROM pg_catalog.pg_class r
            LEFT JOIN pg_catalog.pg_namespace n ON (r.relnamespace = n.oid)
        WHERE r.oid = 20732;
2022-02-09 11:51:08.941 UTC [761178] postgres@stammbaum LOG:  statement: SELECT at.attname, at.attnum, ty.typname
        FROM pg_catalog.pg_attribute at LEFT JOIN pg_catalog.pg_type ty ON (ty.oid = at.atttypid)
        WHERE attrelid=20732::oid AND attnum = ANY (
            (SELECT con.conkey FROM pg_catalog.pg_class rel LEFT OUTER JOIN pg_catalog.pg_constraint con ON con.conrelid=rel.oid
            AND con.contype='p' WHERE rel.relkind IN ('r','s','t', 'p') AND rel.oid = 20732::oid)::oid[])

2022-02-09 11:51:08.952 UTC [761178] postgres@stammbaum LOG:  statement: SELECT at.attname, at.attnum, ty.typname
        FROM pg_catalog.pg_attribute at LEFT JOIN pg_catalog.pg_type ty ON (ty.oid = at.atttypid)
        WHERE attrelid=20732::oid AND attnum = ANY (
            (SELECT con.conkey FROM pg_catalog.pg_class rel LEFT OUTER JOIN pg_catalog.pg_constraint con ON con.conrelid=rel.oid
            AND con.contype='p' WHERE rel.relkind IN ('r','s','t', 'p') AND rel.oid = 20732::oid)::oid[])
```

**Comment by DavidMStraub** [comment] 2022-02-10 08:22
Sorry, I don't see anything related to Gramps there... what do you see in the logs of the grampsweb container?

And does the POST has any effect or also not working?

**Comment by rock31** [comment] 2022-02-10 10:12
Sorry, yes, neither PUT nor POST have any effect on the database. Querying the API from a different device in the network, however, shows the changes. Here is the log from the container:
```
~/gramps-webapidocker$ docker-compose logs -f -t
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.162498341Z [2022-02-10 09:57:01 +0000] [8] [INFO] Starting gunicorn 20.1.0
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.163541254Z [2022-02-10 09:57:01 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.163692974Z [2022-02-10 09:57:01 +0000] [8] [INFO] Using worker: sync
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.170235339Z [2022-02-10 09:57:01 +0000] [9] [INFO] Booting worker with pid: 9
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.246136151Z [2022-02-10 09:57:01 +0000] [10] [INFO] Booting worker with pid: 10
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.277007532Z [2022-02-10 09:57:01 +0000] [11] [INFO] Booting worker with pid: 11
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.302917752Z [2022-02-10 09:57:01 +0000] [12] [INFO] Booting worker with pid: 12
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.401404213Z [2022-02-10 09:57:01 +0000] [13] [INFO] Booting worker with pid: 13
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.433114233Z [2022-02-10 09:57:01 +0000] [14] [INFO] Booting worker with pid: 14
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.469935060Z [2022-02-10 09:57:01 +0000] [15] [INFO] Booting worker with pid: 15
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:01.533705594Z [2022-02-10 09:57:01 +0000] [16] [INFO] Booting worker with pid: 16
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:33.470733061Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:33.531089822Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:33.919396804Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:33.979367569Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:49.887647576Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:49.904653053Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:49.931451539Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:49.969120670Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:49.992079444Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:50.024836357Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:50.302003644Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:57:50.396703983Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:59:12.306283392Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:59:12.310118567Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:59:12.393283193Z Unable to init server: Could not connect: Connection refused
gramps-webapidocker-grampsweb-1  | 2022-02-10T09:59:12.398960845Z Unable to init server: Could not connect: Connection refused
```
Note that the PUT and POST requests were executed minutes after the last timestamp in the log. So there is no log output for the requests themselves.

**Comment by Rahel-A** [comment] 2022-02-10 12:24
> No, definitely not intended.
> 
> Does it mean any write access fails? Also POST, DELETE?
> 
> Any errors in the log?
> 
> @Rahel-A, did it work for you or did you only test read access?

I haven't specifically checked functionality for these REST commands... But through the web interfaces I was able to insert new persons, and I might have tested deleting them. I was definitely able to see the new person through but the web interface, and gramps ui.
Note that in my logs I do see connection refused logs sometimes, probably not more than 4 error messages, most often during initialization, not often afterwards.

**Comment by DavidMStraub** [comment] 2022-02-10 14:53
So what is it that's actually not working? What do you mean by "neither PUT nor POST have any effect on the database. Querying the API from a different device in the network, however, shows the changes."?

BTW, the "Error parsing list of recent DBs" and "Unable to init server" are thrown by gramps itself but are "normal".

Since you are using 8 workers: are you aware of the issue when using more than 1 worker with Postgres? https://github.com/gramps-project/gramps-webapi/pull/265#issuecomment-1009979421

**Comment by DavidMStraub** [comment] 2022-02-10 15:38
>  No, I wasn't aware of that. So, I have to set the workers in the config.cfg?

It's still not documented as we were hoping for the fix in https://github.com/gramps-project/addons-source/pull/523 to be merged before releasing a new API version. Just set the `GUNICORN_NUM_WORKERS` env variable to 1 for the moment.

> When I log into Gramps Desktop, which connects to the Postgres database, these changes are not synchronised. As far as I understand, this means, the Postgres database gets imported once, when the docker container is initalised and does not get synchronised afterwards?

I don't see how this should be possible. Are you sure you are connecting to the exact same database?

**Comment by rock31** [comment] 2022-02-10 15:44
Thanks, I'll try it right away.
There is only one database on my server at the moment.

**Comment by DavidMStraub** [comment] 2022-02-10 15:52
Can you use pgadmin to look at the database when you add objects via the API to see if they appear?

**Comment by rock31** [comment] 2022-02-10 16:14
Yes, nothing is being added.

**Comment by rock31** [comment] 2022-02-13 01:27
> > When I log into Gramps Desktop, which connects to the Postgres database, these changes are not synchronised. As far as I understand, this means, the Postgres database gets imported once, when the docker container is initalised and does not get synchronised afterwards?
> 
> I don't see how this should be possible. Are you sure you are connecting to the exact same database?

I checked the network traffic on the docker container and it does not connect to the PostgreSQL server at any time. In fact, the gramps instance on the docker has no information in `config.database.host` or `config.database.port`. It seems that exporting a Gramps XML from the local Gramps Desktop application, which connects to a remote PostgreSQL server on the local network, and importing this XML in Gramps on the docker instance creates a family tree with sqlite backend and keeps no reference to the PostgreSQL server.
I tried to the set the config on the container manually, but receive the following error:
```
~/gramps-webapidocker$ docker-compose run --entrypoint "" grampsweb gramps --config=database.backend:postgresql --config=database.host:192.168.0.93 --config=database.port:5342 --config=database.path:/root/.gramps/grampsdb
Current Gramps config setting: database.backend:'sqlite'
    New Gramps config setting: database.backend:'postgresql'
Current Gramps config setting: database.host:''
    New Gramps config setting: database.host:'192.168.0.93'
Current Gramps config setting: database.port:''
    New Gramps config setting: database.port:'5342'
Current Gramps config setting: database.path:'/root/.gramps/grampsdb'
    New Gramps config setting: database.path:'/root/.gramps/grampsdb'
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(gramps:1): Gtk-WARNING **: 00:47:16.877: cannot open display:
```

Trying to create a new family tree results in:
```
2022-02-13 01:12:57.991: ERROR: grampsapp.py: line 173: Unhandled exception
Traceback (most recent call last):
  File "/usr/bin/gramps", line 3, in <module>
    app.main()
  File "/usr/lib/python3/dist-packages/gramps/grampsapp.py", line 520, in main
    errors = run()
  File "/usr/lib/python3/dist-packages/gramps/grampsapp.py", line 513, in run
    startcli(error, argpars)
  File "/usr/lib/python3/dist-packages/gramps/cli/grampscli.py", line 380, in startcli
    handler = ArgHandler(dbstate, argparser, climanager)
  File "/usr/lib/python3/dist-packages/gramps/cli/arghandler.py", line 187, in __init__
    self.open = self.__handle_open_option(parser.open, parser.create)
  File "/usr/lib/python3/dist-packages/gramps/cli/arghandler.py", line 237, in __handle_open_option
    db_path, title = self.dbman.create_new_db_cli(title=value,
  File "/usr/lib/python3/dist-packages/gramps/cli/clidbman.py", line 301, in create_new_db_cli
    newdb = make_database(dbid)
  File "/usr/lib/python3/dist-packages/gramps/gen/db/utils.py", line 87, in make_database
    raise Exception("no such database backend: '%s'" % plugin_id)
Exception: no such database backend: 'postgresql'
```

**Comment by DavidMStraub** [comment] 2022-02-13 16:02
Ok, I didn't know you imported an XML. That will just create a new SQLite database. This is why everything works but your Postgres is not updated.

Which grampsweb container version are you using?

**Comment by rock31** [comment] 2022-02-13 16:34
Yeah, sorry... I did not quite understand what the XML import was doing before. 
I'm using v2.2.2 .

**Comment by DavidMStraub** [comment] 2022-02-13 18:53
I'm asking because postgres doesn't work with the released version or the `latest` container. You have to use the `master` branch or the `latest-devel` image.

**Closed** 2022-02-14 14:39 UTC

**Comment by rock31** [comment] 2022-02-14 20:46
@Rahel-A Could you point me in the right direction on how to login to the postgres backend correctly?
The API is connecting just fine, but Gramps on the frontend crashes with this error (which may be the cause for the 500 Internal Server errors I see in the browser):
```
$ docker-compose run --entrypoint "" grampsweb gramps --config=database.backend:postgresql --config=database.host:192.168.0.95 --config=database.port:5432
[+] Running 1/1
 ⠿ Network gramps-webapidocker_default  Created                                                                    0.2s
Current Gramps config setting: database.backend:'sqlite'
    New Gramps config setting: database.backend:'postgresql'
Current Gramps config setting: database.host:''
    New Gramps config setting: database.host:'192.168.0.95'
Current Gramps config setting: database.port:''
    New Gramps config setting: database.port:'5432'
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(gramps:1): Gtk-WARNING **: 20:29:31.724: cannot open display:
```

**Comment by Rahel-A** [comment] 2022-02-14 21:19
@rock31 You'll need to configure a complete environment.
The documentation contains the [minimal configuration](https://gramps-project.github.io/web/Deployment/) required for non-postgresql, but is also required for PostgreSQL... This will get you started. Additionally you just need to pass the [password](https://github.com/gramps-project/web/pull/2/files) of the user that you have configured in your PostgreSQL. So, your files should look something like this:


docker-compose.yml:
```
version: "3.7"

services:
  grampsweb-public:
    build: ./gramps-web # I've gramps source directory checked out
    image: dmstraub/gramps-webapi:latest
    restart: always
    env_file:
      - .postgresql_public.key.env
      - .flask_public.key.env
      - .mail.key.env
    environment:
      TREE: "family_tree_all" # should match postgresql family tree name
      BASE_URL: "https://yoururl.com/"
      GRAMPSJS_VERSION: "v0.10.0"
      MEDIA_BASE_DIR: "/all_media/files/"
    volumes:
      - gramps_users_public:/app/users
      - gramps_index_public:/app/indexdir
      - gramps_thumb_cache_public:/app/thumbnail_cache
      - ./data/gramps_db_public:/root/.gramps/grampsdb
      - gramps_media:/all_media:ro
    networks:
      - gramps-backend
```
postgresql_public.key.env
```
# the password for your 'user'
POSTGRES_PASSWORD='pass'
```
data/gramps_db_public/12356wer/settings.ini
```
;; Gramps key file
;; Automatically created at 2021/12/12 19:50:00
;; this file is generated when you connect the desktop gramps ui to postgresql db

[database]
dbname='family_tree_all'
;; I've changed host to match my docker container's name:
host='postgres_db_public' 
port='5432'
;; your postgresql 'user'
user='user'
```
data/gramps_db_public/12356wer/name.txt
```
family_tree_all
```
data/gramps_db_public/12356wer/database.txt
```
postgresql
```

**Comment by Rahel-A** [comment] 2022-02-14 23:38
I've realised that I didn't import using xml, so I'm not sure how you would translate my settings ini to the equivalent of updating your xml config... Maybe @DavidMStraub can comment on how you would set the user in your use case?

**Comment by rock31** [comment] 2022-02-15 19:13
Thanks! The API is running without Auth for the moment and REST requests are relayed to the database. So it's working! The `500 Internal Server` errors I mentioned before are only occuring when the parameter `locale` is in the request, which is probably due to this error and maybe related to #86 ?:
```
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445549644Z [2022-02-15 18:13:18 +0000] [9] [ERROR] Error handling request /api/sources/?rules=%7B%22rules%22%3A%5B%7B%22name%22%3A%22HasTag%22%2C%22values%22%3A%5B%22Blog%22%5D%7D%5D%7D&pagesize=1&sort=-change&locale=de&profile=all&extend=all
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445695364Z Traceback (most recent call last):
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445727049Z   File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 136, in handle
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445754623Z     self.handle_request(listener, req, client, addr)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445800363Z   File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/sync.py", line 179, in handle_request
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445827362Z     respiter = self.wsgi(environ, resp.start_response)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445851436Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2091, in __call__
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445876232Z     return self.wsgi_app(environ, start_response)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445899584Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2076, in wsgi_app
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445923398Z     response = self.handle_exception(e)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445946805Z   File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.445971379Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446009971Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446035804Z     response = self.full_dispatch_request()
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446095859Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446131970Z     rv = self.handle_user_exception(e)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446158562Z   File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446183265Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446456373Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446489687Z     rv = self.dispatch_request()
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446721999Z   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446747684Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446766425Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/auth.py", line 45, in wrapper
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446784295Z     return func(*args, **kwargs)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446801739Z   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 84, in view
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446891034Z     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446918571Z   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 158, in dispatch_request
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446937478Z     return current_app.ensure_sync(meth)(*args, **kwargs)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446955737Z   File "/usr/local/lib/python3.9/dist-packages/webargs/core.py", line 450, in wrapper
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446973718Z     return func(*args, **kwargs)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.446991125Z   File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/api/resources/base.py", line 371, in get
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447009051Z     handles = query_method(sort_handles=True, locale=locale)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447026384Z   File "/usr/lib/python3/dist-packages/gramps/plugins/db/dbapi/dbapi.py", line 458, in get_source_handles
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447044032Z     'COLLATE "%s"' % self._collation(locale))
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447061291Z   File "/usr/lib/python3/dist-packages/gramps/plugins/db/dbapi/dbapi.py", line 232, in _collation
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447078976Z     collation = self.dbapi.check_collation(locale)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447096402Z   File "/root/.gramps/gramps51/plugins/PostgreSQL/postgresql.py", line 137, in check_collation
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447114309Z     self.execute('CREATE COLLATION "%s"'
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447131753Z   File "/root/.gramps/gramps51/plugins/PostgreSQL/postgresql.py", line 168, in execute
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447150049Z     self.__cursor.execute(sql, args, **kwargs)
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447167531Z psycopg2.errors.InvalidParameterValue: could not create locale "de": No such file or directory
gramps-webapidocker-grampsweb-1  | 2022-02-15T18:13:18.447185493Z DETAIL:  The operating system could not find any locale data for the locale name "de".
```
Is this why you have the gramps source directory checked out?

**Comment by DavidMStraub** [comment] 2022-02-21 18:43
@rock31, I am trying to reproduce these steps to get a minimal example for the docs. However I'm failing to import the XML into the Postgres DB because I don't see any way to supply the username and password on the command line:

```
docker-compose run --entrypoint "" grampsweb gramps -C postgres -i example.gramps --config=database.backend:postgresql --config=database.host:postgres_gramps --config=database.port:5432
```
```
ERROR: Database connection failed.

fe_sendauth: no password supplied
```

Did you ever get this to work?

**Comment by Nick-Hall** [comment] 2022-02-21 18:50
Try using the `-U` or `--username=USERNAME` and `-P` or `--password=PASSWORD` command line options.

**Comment by DavidMStraub** [comment] 2022-02-21 18:55
Thanks! How could I miss that :facepalm:

**Comment by DavidMStraub** [comment] 2022-02-22 16:17
Getting closer ... @Rahel-A did you add the `user` key to `settings.ini` manually? In my case it is not added, and I also understand this from the source code as the `database.user` key is not registered with the config manager. Even though I can import the XML fine now using the `--username` command line flag, I cannot run web API because there is no way (apart from manually editing the `settings.ini` which I want to avoid) to specify the Postgres username, and the default seems to be `root`.

**Comment by Rahel-A** [comment] 2022-02-22 16:33
> @Rahel-A did you add the `user` key to `settings.ini` manually?
Yeah I think I might have added that manually.
I just created a new "connection" to my database in gramps UI. Each time I open my family tree in gramps UI, I have to input my username and password, which doesn't get saved in settings.ini.

**Comment by Nick-Hall** [comment] 2022-02-22 18:15
It looks like you need to pass a `POSTGRES_USERNAME` when you instantiate a `WebDbManager` [here](https://github.com/gramps-project/gramps-webapi/blob/97a929e64bf26d733e9f971ffa304d3dd42909a5/gramps_webapi/app.py#L78
) and then pass it to the `open_activate` method of the session manager [here](https://github.com/gramps-project/gramps-webapi/blob/97a929e64bf26d733e9f971ffa304d3dd42909a5/gramps_webapi/dbmanager.py#L99
).

**Comment by DavidMStraub** [comment] 2022-02-22 19:00
Yes, exactly, that's what I would propose as well - treat it just like the password. @Rahel-A would you like to add it?
