### ISSUE TITLE
Menu topic "reports" generates error 504

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/gramps-webapi#444] opened 2023-10-30 10:03 UTC
When selecting the last menu topic "Reports" an 504 error occures.

**Comment by hartenthaler** [comment] 2023-10-31 11:12
This error happens not only when selecting the menu "Reports". It happens always when I change the focus to the tab "Lists".
![Screenshot (430)](https://github.com/gramps-project/gramps-webapi/assets/6324175/c12e2c55-b8d0-4740-8c38-b85a4c4c8ca5)

**Comment by DavidMStraub** [comment] 2023-10-31 11:28
Is it only happening with the "events" tab or also for "people" etc.? 

Can you do me a favour and post a screenshot of the "Network" tab in the browser development console (F12) while opening the peoples table? 

504 means that there was a timeout while waiting for the server response, which is quite surprising, because displaying the paged list should be blazing fast even for thousands of events.

I suspect that it's still related to the reports page timing out and the popup is simply popping up in the wrong moment. Also, if the error would be caused by the events view itself, you wouldn't see the events...

**Comment by hartenthaler** [comment] 2023-11-01 23:09
Today, I was not able to reproduce that error. Sorry.

Yesterday the 504 error happened only on the events tab after defining a filter. Then it happened always when I selected that tab.

When opening the menu "Reports" there is still a 504 error after about 40 seconds.

**Comment by DavidMStraub** [comment] 2023-11-19 17:10
This should be fixed in Web API [v1.4.1](https://github.com/gramps-project/gramps-webapi/releases/tag/v1.4.1).

**Closed by DavidMStraub** 2023-11-19 17:10 UTC
Labels: performance
