### ISSUE TITLE
Support for postgresql gramps addon

### ISSUE THREAD

**Issue by Rahel-A** [gramps-project/gramps-webapi#255] opened 2021-12-14 21:36 UTC
I've only recently setup my family tree, and I ended up using postgresql to make remote access easier for myself. 
I tried copying my database settings over to gramps-webapi however I don't think postgresql is supported as  ALLOWED_DB_BACKENDS is set to only sqlite.

I hadn't noticed this project and Gramps.js, otherwise I might have just set it up in sqlite.
I don't mind switching over or just importing my database normally to gramps-webapi as described in the documentation, however I thought I might ask here before I do that.
Is it possible for this project to communicate with postgresql database already setup and running in a docker container? I wouldn't mind working on this myself either if it isn't too much effort.

**Comment by DavidMStraub** [comment] 2021-12-14 21:42
Yes, I think that should definitely be possible, useful, and not difficult to add! If you want to give it a try, that would be great.

In fact I am still dreaming of a future "Gramps Web API Hub" hosting many databases on a single host. This would definitely require Postgres (or something similar) instead of SQLite. Unfortunately it's not possible with the current Postgres addon which assumes only one Gramps DB per Postgres schema.

**Comment by DavidMStraub** [comment] 2021-12-30 12:39
While looking into Postgres, I also found the time to finish an addon I had thought about for some time, allowing to store more than one tree in a Postgres database. I would appreciate feedback: https://github.com/gramps-project/addons-source/pull/524

**Comment by DavidMStraub** [comment] 2022-01-10 18:53
Can be closed once https://github.com/gramps-project/addons-source/pull/523 is merged.

**Comment by DavidMStraub** [comment] 2022-01-27 16:18
I'm not sure how to proceed with the next release with #265 merged but https://github.com/gramps-project/addons-source/pull/523 not yet. I think to avoid confusion we should either add something to the docs about the 1-thread workaround or disable Postgres support for the moment. What do you think, @Rahel-A?

**Comment by rock31** [comment] 2022-02-06 14:02
Hi, 
I'm not sure if this is the right place to ask, but I'm having trouble importing my PostgreSQL database I guess, I'm just missing something in the configuration?

> version: "3.7"
services:
  grampsweb:
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "8080:5000"
    environment:
      TREE: "stammbaum"
      SECRET_KEY: "..."
      DISABLE_AUTH: True
      POSTGRES_PASSWORD: "..."
    volumes:
      - gramps_users:/app/users
      - gramps_index:/app/indexdir
      - gramps_thumb_cache:/app/thumbnail_cache
      - ~/gramps_db:/root/.gramps/grampsdb
      - ~/gramps_media:/app/media
volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:

I have a Postgres server running on a Pi that serves a few small React apps through PostgREST. The Docker image of the Web-API and Gramps.js is deployed correctly on the Pi, but the following error occurs when trying to import the Gramps XML:

> ~/gramps-webapidocker$ docker-compose run grampsweb     gramps -C 'stammbaum'     -i /root/.gramps/grampsdb/stammbaum.gramps     --config=database.backend:postgresql     --config=database.path:/root/.gramps/grampsdb
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 130, in <module>
    cli(
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 43, in cli
    ctx.obj = create_app()
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/app.py", line 75, in create_app
    app.config["DB_MANAGER"] = WebDbManager(name=app.config["TREE"])
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 46, in __init__
    self.path = self._get_path()
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 55, in _get_path
    raise ValueError(
ValueError: Database path for family tree 'stammbaum' not found in database directory /root/.gramps/grampsdb

**Comment by DavidMStraub** [comment] 2022-02-06 15:19
Hi, I think you just have to change the database directory to point to the correct one in the container, see the corresponding import command for the demo Heroku app:

https://github.com/gramps-project/Gramps.js/blob/main/demo/Dockerfile#L12

Let me know if it works - we should add it to the docs.

**Comment by rock31** [comment] 2022-02-06 16:55
I fear, it's just me not understanding the file structure of docker...
The Gramps XML is in ~/gramps_db which points to /root/.gramps/grampsdb. I tried running the import command in different variations (with 'app' instead of 'root', sqlite instead of postgresql, absolute paths, putting the Gramps XML in the same directory as the docker file), however, the error is always the same.

**Comment by DavidMStraub** [comment] 2022-02-06 19:18
Ok let's go step by step. You have the `grampsweb` container running with compose.

Now please run (differently from above!) the command [from the docs](https://gramps-project.github.io/web/Deployment/#step-5-import-database):

```
docker-compose run grampsweb \
    gramps -C stammbaum \
    -i /root/.gramps/grampsdb/stammbaum.gramps \
    --config=database.backend:sqlite \
    --config=database.path:/root/.gramps/grampsdb
```
Assuming you have copied/mounted the XML file to the right location. To check this worked, run
```
docker-compose run grampsweb gramps -L
```

**Comment by rock31** [comment] 2022-02-06 19:29
> ~/gramps-webapidocker$ docker-compose run grampsweb \
/root/.gramps>     gramps -C stammbaum \
>     -i /root/.gramps/grampsdb/stammbaum.gramps \
>     --config=database.backend:sqlite \
>     --config=database.path:/root/.gramps/grampsdb
[+] Running 1/1
 ⠿ Network gramps-webapidocker_default  Created                                                                    0.2s
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 130, in <module>
    cli(
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 43, in cli
    ctx.obj = create_app()
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/app.py", line 75, in create_app
    app.config["DB_MANAGER"] = WebDbManager(name=app.config["TREE"])
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 46, in __init__
    self.path = self._get_path()
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 55, in _get_path
    raise ValueError(
ValueError: Database path for family tree 'stammbaum' not found in database directory /root/.gramps/grampsdb

> ~/gramps-webapidocker$ docker-compose run grampsweb gramps -L
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 130, in <module>
    cli(
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/__main__.py", line 43, in cli
    ctx.obj = create_app()
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/app.py", line 75, in create_app
    app.config["DB_MANAGER"] = WebDbManager(name=app.config["TREE"])
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 46, in __init__
    self.path = self._get_path()
  File "/usr/local/lib/python3.9/dist-packages/gramps_webapi/dbmanager.py", line 55, in _get_path
    raise ValueError(
ValueError: Database path for family tree 'stammbaum' not found in database directory /root/.gramps/grampsdb

Maybe the stammbaum.gramps file doesn't get copied to the container?

**Comment by DavidMStraub** [comment] 2022-02-06 19:40
Oh-oh, I start to suspect it's my fault ;) Can you please try

```
docker-compose run --entrypoint "" grampsweb \
gramps -C stammbaum \
    -i /root/.gramps/grampsdb/stammbaum.gramps \
    --config=database.backend:sqlite \
    --config=database.path:/root/.gramps/grampsdb
```

**Comment by rock31** [comment] 2022-02-06 19:51
> ~/gramps-webapidocker$ docker-compose run --entrypoint "" grampsweb gramps -C stammbaum     -i /root/.gramps/grampsdb/stammbaum.gramps     --config=database.backend:sqlite     --config=database.path:/root/.gramps/grampsdb
[+] Running 1/1
 ⠿ Network gramps-webapidocker_default  Created                                                                    0.2s
Current Gramps config setting: database.backend:'sqlite'
    New Gramps config setting: database.backend:'sqlite'
Current Gramps config setting: database.path:'/root/.gramps/grampsdb'
    New Gramps config setting: database.path:'/root/.gramps/grampsdb'
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Error: Import file /root/.gramps/grampsdb/stammbaum.gramps not found.

Should I try with `database.backend.sqlite`?

**Comment by DavidMStraub** [comment] 2022-02-06 21:29
OK, we got past the entrypoint. Now the problem is that your XML is not found. Do you have the volume

```
      - ~/gramps_db:/root/.gramps/grampsdb
```

in your compose? Did you copy `stammbaum.gramps` to `~/gramps_db` on the host?

**Comment by rock31** [comment] 2022-02-06 22:25
```
Current Gramps config setting: database.backend:'sqlite'
    New Gramps config setting: database.backend:'sqlite'
Current Gramps config setting: database.path:'/root/.gramps/grampsdb'
    New Gramps config setting: database.path:'/root/.gramps/grampsdb'
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(gramps:1): Gtk-CRITICAL **: 21:38:08.028: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Unable to init server: Could not connect: Connection refused
Opened successfully!
Importing: file /root/.gramps/grampsdb/stammbaum.gramps, format gramps.
100%Cleaning up.
```
I had a typo in the compose file. One underscore too many. It's working perfectly now. Thank you! And sorry for cluttering this thread.

**Comment by DavidMStraub** [comment] 2022-02-07 06:35
Great, no problem! Just to confirm: it only worked with the additional `--entrypoint ""` parameter when importing the `.gramps`, right? Because this is currently missing in the docs.

**Comment by rock31** [comment] 2022-02-07 06:43
Yes, the entrypoint parameter made the difference.

**Comment by DavidMStraub** [comment] 2022-02-23 20:37
I still didn't manage to get Postgres to work fully. My problem is that, whenever I set the frontend language in Gramps Web to something other than English, Postgres throws errors like

```
The operating system could not find any locale data for the locale name "de".
CREATE COLLATION IF NOT EXISTS "de"(LOCALE = 'de')
The operating system could not find any locale data for the locale name "it".
CREATE COLLATION IF NOT EXISTS "it"(LOCALE = 'it')
```

I have installed all locales in the Postgres container using `apt install locales-all`. The problem is that there are no locales names `de` or `it`, only `de_DE` and `it_IT`.

I think the issue is that `GrampsLocale.lang` is usually not a valid locale name. 

I am not sure if it's an issue with `get_locale_for_language` in Web API or with Gramps...

**Comment by rock31** [comment] 2022-02-23 21:15
It's a problem with [Gramps](https://gramps-project.org/bugs/view.php?id=10461). My workaround was to add a locale alias on the PostgreSQL server, but that's not ideal for production. Maybe a lookup table in the Web-API could solve that issue?

**Comment by DavidMStraub** [comment] 2022-02-26 12:55
I implented the lookup table in #275 but it didn't solve my problem: now I get

```
grampsweb_1        | psycopg2.errors.InvalidParameterValue: encoding "UTF8" does not match locale "de_DE"
grampsweb_1        | DETAIL:  The chosen LC_CTYPE setting requires encoding "LATIN1".
```

Next I'll try to append `.UTF-8` to all locales but I'm unsure whether this is a good idea.

**Comment by Nick-Hall** [comment] 2022-02-26 14:22
Use the command `locale -a` to list the locales installed on your system.

**Comment by DavidMStraub** [comment] 2022-03-23 09:03
Workaround #275 merged, closing issue.

**Closed by DavidMStraub** 2022-03-23 09:03 UTC
Labels: enhancement
