### ISSUE TITLE
Julian date not displayed correctly

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/gramps-webapi#454] opened 2023-11-09 10:53 UTC
There is no support for calendar systems:
- no possibility to enter a date using another calendar
- dates in other calendar systems are shown as if they are using the Gregorian calendar

**Comment by DavidMStraub** [comment] 2023-11-11 12:04
Thanks for the feedback. Comments:

1. This is a frontend question (no worries, I know it's confusing)
2. It's not entirely correct because non-Gregorian calendars *are* correctly displayed in most cases, see screenshot below
3. That non-Gregorian dates cannot be *edited* is known and there is a feature request already: https://github.com/gramps-project/Gramps.js/issues/273

Thus, closing this.

![grafik](https://github.com/gramps-project/gramps-webapi/assets/10965193/bc928bdb-a3ff-4203-87e3-75b603fd9828)

**Comment by hartenthaler** [comment] 2023-11-11 12:20
I tested with Julian's dates in the GEDCOM. They are listed as if they are Gregorian. There is no calendar indicated in brackets behind the date. So it is not only about editing other calendar dates.

**Comment by DavidMStraub** [comment] 2023-11-11 13:35
You are right, if it's about GEDCOM import, it's a question for Gramps core. I suggest to ask in Gramps discourse first with an example, because in principle Gramps *does* handle GEDCOM non-Gregorian calendars just fine (see https://github.com/gramps-project/gramps/blob/master/gramps/plugins/lib/libgedcom.py#L837-L841), so it might also be a non-standards compliant input GEDCOM.

**Comment by hartenthaler** [comment] 2023-11-11 14:33
I just checked it. Gramps is importing Julian dates correctly as far as I can see.
![Screenshot (441)](https://github.com/gramps-project/gramps-webapi/assets/6324175/1755b53c-3b65-471a-b7a2-4e2d02f2f94c)


But Gramps Web does not show it correctly.
![Screenshot (442)](https://github.com/gramps-project/gramps-webapi/assets/6324175/07b013c2-a8e6-4461-a680-93282e3df8e7)

**Comment by DavidMStraub** [comment] 2023-11-11 14:36
Oh, that's surprising. Reopened.

**Comment by DavidMStraub** [comment] 2023-12-29 07:30
I looked into this again and was not able to reproduce this behaviour; for me all Julian dates are shown correctly, also in the person view:

![grafik](https://github.com/gramps-project/gramps-webapi/assets/10965193/08d49c93-6eb1-46f5-8057-4e8dd4bab69d)

Thus I'll close this issue for now (concerning entering Julian dates, we still have https://github.com/gramps-project/Gramps.js/issues/273).

**Closed by DavidMStraub** 2023-12-29 07:30 UTC
