### ISSUE TITLE
Some places don't have a title set

### ISSUE THREAD

**Issue by lenzls** [gramps-project/gramps-webapi#194] opened 2021-07-18 10:27 UTC
Hello,

I've noticed, that quite a lot of my places have an empty name in Gramps.js. The reason seems to be that those places do not have the title attribute set from gramps-webapi.

On gramps desktop, I can't really see a difference between places that have a title in the webapi and that don't.

Could this be an error in the webapi, or is there something wrong with my data?

### With title
![scrot_2021-07-18_12-23-11_screenshot](https://user-images.githubusercontent.com/263263/126063780-66cd0fda-cb50-4756-a36a-70fc9fdfc3ab.png)
```
[
  {
    "alt_loc": [],
    "alt_names": [],
    "change": 1490502228,
    "citation_list": [],
    "code": "",
    "gramps_id": "P0074",
    "handle": "c0840e47d017e26b6b9f5bed94c",
    "lat": "",
    "long": "",
    "media_list": [],
    "name": {
      "date": {
        "calendar": 0,
        "dateval": [
          0,
          0,
          0,
          false
        ],
        "format": null,
        "modifier": 0,
        "newyear": 0,
        "quality": 0,
        "sortval": 0,
        "text": "",
        "year": 0
      },
      "lang": "",
      "value": "Armenhaus"
    },
    "note_list": [],
    "place_type": "Locality",
    "placeref_list": [
      {
        "date": {
          "calendar": 0,
          "dateval": [
            0,
            0,
            0,
            false
          ],
          "format": null,
          "modifier": 0,
          "newyear": 0,
          "quality": 0,
          "sortval": 0,
          "text": "",
          "year": 0
        },
        "ref": "bf90cf6adcd65a9a731c72bf75a"
      }
    ],
    "private": false,
    "tag_list": [],
    "title": "Adenbach (Armenhaus)",
    "urls": []
  }
]
```

### Without title
![scrot_2021-07-18_12-23-18_screenshot](https://user-images.githubusercontent.com/263263/126063778-6e6bc488-9968-4158-b978-afe47a4facca.png)
```
[
  {
    "alt_loc": [],
    "alt_names": [],
    "change": 1517438417,
    "citation_list": [],
    "code": "",
    "gramps_id": "P0175",
    "handle": "dcd0faacd911e181aa0c7ff5e8d",
    "lat": "",
    "long": "",
    "media_list": [],
    "name": {
      "date": {
        "calendar": 0,
        "dateval": [
          0,
          0,
          0,
          false
        ],
        "format": null,
        "modifier": 0,
        "newyear": 0,
        "quality": 0,
        "sortval": 0,
        "text": "",
        "year": 0
      },
      "lang": "",
      "value": "Wohnung Busch Jacob"
    },
    "note_list": [],
    "place_type": "Wohnung",
    "placeref_list": [
      {
        "date": {
          "calendar": 0,
          "dateval": [
            0,
            0,
            0,
            false
          ],
          "format": null,
          "modifier": 0,
          "newyear": 0,
          "quality": 0,
          "sortval": 0,
          "text": "",
          "year": 0
        },
        "ref": "bcd0aa035c72341109f"
      }
    ],
    "private": false,
    "tag_list": [],
    "title": "",
    "urls": []
  }
]
```

**Comment by lenzls** [comment] 2021-07-18 10:57
Just realized that this is probably the same as #190. If yes, please close without hesitation.

**Comment by DavidMStraub** [comment] 2021-07-18 11:22
Thanks for reporting, yes I think it's a duplicate of #190 and it should be fixed. Dealing with the different dates and languages in full generality is a bit tricky.

**Closed by DavidMStraub** 2021-07-18 11:22 UTC
